import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, Building2, CalendarClock, CreditCard, Eye, Loader2, RefreshCw, RotateCcw, Search, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { parseApiError } from "@/utils/error";
import { salesApi, type CustomerOutstandingSummary, type SalesInvoiceDocument } from "./sales.api";
import { InvoiceProcessDialog, SalesDetailDialog } from "./SalesDocumentList";
import SalesReturnDialog from "./SalesReturnDialog";

const rupiah = (value: number) => `Rp ${Number(value || 0).toLocaleString("id-ID")}`;
const date = (value?: string | null) => value ? new Date(value).toLocaleDateString("id-ID") : "-";

export default function CustomerOutstandingPage({ canPay, canReturn }: { canPay: boolean; canReturn: boolean }) {
  const [rows, setRows] = useState<CustomerOutstandingSummary[]>([]);
  const [page, setPage] = useState(1), [limit, setLimit] = useState(20), [totalPages, setTotalPages] = useState(1);
  const [search, setSearch] = useState(""), [query, setQuery] = useState("");
  const [selected, setSelected] = useState<{ customer: CustomerOutstandingSummary; invoices: SalesInvoiceDocument[] } | null>(null);
  const [detail, setDetail] = useState<SalesInvoiceDocument | null>(null), [payment, setPayment] = useState<SalesInvoiceDocument | null>(null);
  const [returnInvoiceId, setReturnInvoiceId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true), [error, setError] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => { setQuery(search.trim()); setPage(1); }, 300); return () => window.clearTimeout(timer); }, [search]);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await salesApi.customerOutstanding(page, limit, query); setRows(Array.isArray(result.data) ? result.data : []); setTotalPages(Math.max(1, Number(result.meta?.totalPages) || 1)); } catch (caught) { setError(parseApiError(caught)); } finally { setLoading(false); } }, [page, limit, query]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  const open = async (customer: CustomerOutstandingSummary) => { setLoading(true); setError(""); try { setSelected(await salesApi.customerOutstandingInvoices(customer.customerId)); } catch (caught) { setError(parseApiError(caught)); } finally { setLoading(false); } };
  const refreshSelected = async () => { if (selected) setSelected(await salesApi.customerOutstandingInvoices(selected.customer.customerId)); await load(); };
  return <div className="space-y-4 pb-8">
    <section className="rounded-xl border bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2">{selected&&<Button variant="ghost" size="sm" onClick={()=>setSelected(null)}><ArrowLeft className="mr-1 h-4 w-4"/>Kembali</Button>}<div><h2 className="flex items-center gap-2 text-base font-black text-slate-900"><Users className="h-5 w-5 text-blue-600"/>{selected?`Piutang: ${selected.customer.customerName}`:"Customer Financial Summary"}</h2><p className="mt-1 text-xs text-slate-500">{selected?"Faktur COMPLETED yang masih belum lunas.":"Pilih customer untuk melihat faktur, detail, pembayaran, dan retur."}</p></div></div><Button variant="outline" size="sm" onClick={()=>void (selected?refreshSelected():load())}><RefreshCw className="mr-1 h-4 w-4"/>Refresh</Button></div>{!selected&&<div className="mt-4 flex gap-2"><label className="relative flex-1 sm:max-w-80"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input className="sales-input pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari customer atau telepon..."/></label><select className="sales-input w-auto" value={limit} onChange={e=>{setLimit(Number(e.target.value));setPage(1)}}>{[20,30,50,100].map(v=><option key={v} value={v}>{v}</option>)}</select></div>}</section>
    {error&&<div className="flex gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700"><AlertTriangle className="h-5 w-5"/>{error}</div>}
    {loading?<div className="flex min-h-52 items-center justify-center"><Loader2 className="mr-2 h-6 w-6 animate-spin"/>Memuat piutang...</div>:!selected?<SummaryCards rows={rows} open={open}/>:<InvoiceCards invoices={selected.invoices} canPay={canPay} canReturn={canReturn} onDetail={id=>void salesApi.invoice(id).then(setDetail).catch(caught=>setError(parseApiError(caught)))} onPay={setPayment} onReturn={setReturnInvoiceId}/>} 
    {!loading&&!selected&&<div className="flex items-center justify-between text-xs text-slate-500"><span>Halaman {page} dari {totalPages}</span><div className="flex gap-2"><Button variant="outline" disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Sebelumnya</Button><Button variant="outline" disabled={page>=totalPages} onClick={()=>setPage(v=>v+1)}>Berikutnya</Button></div></div>}
    {detail&&<SalesDetailDialog kind="SI" data={detail} accountsPermission={canPay} canApprove={false} onClose={()=>setDetail(null)} onChanged={async()=>{setDetail(null);await refreshSelected()}}/>}
    {payment&&<InvoiceProcessDialog invoice={payment} canApprove={false} canReceivePayment={canPay} paymentOnly onClose={()=>setPayment(null)} onProcessed={async()=>{setPayment(null);await refreshSelected()}}/>}
    {returnInvoiceId&&<SalesReturnDialog invoiceId={returnInvoiceId} onClose={()=>setReturnInvoiceId(null)} onSaved={async()=>{setReturnInvoiceId(null);await refreshSelected()}}/>}
  </div>;
}

function SummaryCards({rows,open}:{rows:CustomerOutstandingSummary[];open:(row:CustomerOutstandingSummary)=>Promise<void>}) { if(!rows.length)return <div className="rounded-xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">Tidak ada piutang customer aktif.</div>; return <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map(row=>{const overdue=!!row.oldestDueDate&&new Date(row.oldestDueDate)<new Date();return <button type="button" key={row.customerId} onClick={()=>void open(row)} className={`group rounded-xl border p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md focus:ring-2 focus:ring-blue-500 ${overdue?"border-red-300 bg-red-50":"border-blue-200 bg-white"}`}><div className="flex justify-between"><span className="rounded-lg bg-blue-50 p-2 text-blue-600 group-hover:bg-blue-600 group-hover:text-white"><Building2 className="h-5 w-5"/></span><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-black">{row.unpaidInvoiceCount} DOKUMEN AKTIF</span></div><h3 className="mt-3 font-black uppercase">{row.customerName}</h3><div className="mt-4 flex justify-between border-t pt-3 text-xs"><span className="font-bold text-slate-500">Total Outstanding</span><strong className="text-red-600">{rupiah(row.outstandingAmount)}</strong></div>{overdue&&<p className="mt-2 text-[10px] font-black text-red-600">LEWAT TENGGAT · {date(row.oldestDueDate)}</p>}</button>})}</div> }

function InvoiceCards({invoices,canPay,canReturn,onDetail,onPay,onReturn}:{invoices:SalesInvoiceDocument[];canPay:boolean;canReturn:boolean;onDetail:(id:string)=>void;onPay:(row:SalesInvoiceDocument)=>void;onReturn:(id:string)=>void}) { if(!invoices.length)return <div className="rounded-xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">Tidak ada faktur aktif.</div>; return <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{invoices.map(invoice=>{const overdue=!!invoice.dueDate&&new Date(invoice.dueDate)<new Date();return <article key={invoice.salesInvoiceId} className={`flex flex-col justify-between rounded-xl border p-4 shadow-sm ${overdue?"border-red-300 bg-red-50":"border-slate-200 bg-white"}`}><div><div className="flex justify-between gap-2"><strong>{invoice.salesInvoiceNumber}</strong><span className="rounded-full bg-amber-100 px-2 py-1 text-[9px] font-black text-amber-800">{invoice.statusPayment}</span></div>{overdue&&<p className="mt-2 rounded bg-red-600 px-2 py-1 text-center text-[9px] font-black text-white">LEWAT TENGGAT</p>}<div className="mt-3 space-y-1 rounded-lg bg-white/70 p-3 text-xs"><div className="flex justify-between"><span>Total</span><strong>{rupiah(invoice.invoiceTotal)}</strong></div><div className="flex justify-between"><span>Sudah dibayar</span><strong>{rupiah(invoice.paidAmount)}</strong></div><div className="flex justify-between border-t pt-1 text-red-600"><span>Sisa piutang</span><strong>{rupiah(invoice.outstandingAmount)}</strong></div><div className="flex justify-between"><span><CalendarClock className="mr-1 inline h-3 w-3"/>Jatuh tempo</span><strong>{date(invoice.dueDate)}</strong></div></div></div><div className="mt-3 flex flex-wrap justify-end gap-2 border-t pt-3"><Button variant="outline" size="sm" onClick={()=>onDetail(invoice.salesInvoiceId)}><Eye className="mr-1 h-4 w-4"/>Detail</Button>{canReturn&&<Button variant="outline" size="sm" onClick={()=>onReturn(invoice.salesInvoiceId)}><RotateCcw className="mr-1 h-4 w-4"/>Retur</Button>}{canPay&&<Button size="sm" onClick={()=>onPay(invoice)}><CreditCard className="mr-1 h-4 w-4"/>Bayar</Button>}</div></article>})}</div> }
