import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Loader2, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogOverlay, DialogTitle } from "@/components/ui/dialog";
import { parseApiError } from "@/utils/error";
import { salesApi, type SalesFinancialAccount, type SalesProductOption, type SalesReturnContext } from "./sales.api";
import { systemConfigApi } from "@/features/system/system-configuration.api";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";

export default function SalesReturnDialog({ invoiceId, onClose, onSaved }: { invoiceId: string; onClose: () => void; onSaved: (message: string) => void | Promise<void> }) {
  const [context, setContext] = useState<SalesReturnContext | null>(null);
  const [accounts, setAccounts] = useState<SalesFinancialAccount[]>([]);
  const [values, setValues] = useState<Record<string, { quantity: number; bonusQuantity: number; reason: string }>>({});
  const [resolution, setResolution] = useState<"REFUND" | "REPLACEMENT">("REFUND");
  const [accountId, setAccountId] = useState("");
  const [method, setMethod] = useState("CASH");
  const [note, setNote] = useState("");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const [printAfterComplete, setPrintAfterComplete] = useState(false);
  const [products, setProducts] = useState<SalesProductOption[]>([]);
  const [replacementRows, setReplacementRows] = useState<Array<{ productUnitId: string; quantity: number; unitPrice: number }>>([{ productUnitId: "", quantity: 0, unitPrice: 0 }]);
  const [dueDate, setDueDate] = useState("");
  const [pendingStatus, setPendingStatus] = useState<"DRAFT" | "COMPLETED" | null>(null);
  const [showForm, setShowForm] = useState(true);
  useEffect(() => { void Promise.all([salesApi.returnContext(invoiceId), salesApi.accounts()]).then(async ([data, accountRows]) => { setContext(data); setShowForm(!data.returns?.length); setAccounts(accountRows); setAccountId(accountRows.find(a=>a.accountType==="CASH")?.financialAccountId ?? accountRows[0]?.financialAccountId ?? ""); setProducts(await salesApi.products(data.customerId ?? undefined)); }).catch(caught=>setError(parseApiError(caught))); }, [invoiceId]);
  const total = useMemo(() => context?.details.reduce((sum, line) => sum + (values[line.salesInvoiceDetailId]?.quantity ?? 0) * (line.soldQuantity ? line.subtotal / line.soldQuantity : line.unitPrice), 0) ?? 0, [context, values]);
  const replacementTotal = useMemo(() => replacementRows.reduce((sum,row)=>sum+row.quantity*row.unitPrice,0),[replacementRows]);
  const submit = async (status: "DRAFT" | "COMPLETED") => {
    setSaving(true); setError("");
    try { const credit = Math.max(0,total-(context?.outstandingAmount??0)); const difference = Math.max(0,replacementTotal-credit); const replacementItems = replacementRows.filter(row=>row.productUnitId&&row.quantity>0); if(resolution==="REPLACEMENT"&&!replacementItems.length) throw new Error("Minimal satu barang pengganti harus dipilih."); if(resolution==="REPLACEMENT"&&context?.partyType==="CUSTOMER"&&difference>0&&!dueDate) throw new Error("Tanggal jatuh tempo wajib diisi jika nilai barang pengganti masih memiliki selisih."); const result = await salesApi.createReturn(invoiceId, { returnDate: new Date().toISOString(), status, resolutionType: resolution, financialAccountId: accountId || undefined, refundPaymentMethod: method, note: note || undefined, items: context?.details.map(line => ({ salesInvoiceDetailId: line.salesInvoiceDetailId, quantity: values[line.salesInvoiceDetailId]?.quantity ?? 0, bonusQuantity: values[line.salesInvoiceDetailId]?.bonusQuantity ?? 0, reason: values[line.salesInvoiceDetailId]?.reason || undefined })), ...(resolution==="REPLACEMENT"?{replacementInvoice:{customerId:context?.customerId??undefined,partyType:context?.partyType??"GUEST",customerName:context?.customerName,salesChannel:"MANUAL",paymentType:context?.partyType==="GUEST"?"CASH":"CREDIT",invoiceDate:new Date().toISOString(),dueDate:dueDate||undefined,discountAmount:0,status:"COMPLETED",snapshotMode:"IGNORE",note:`Barang pengganti dari ${context?.salesInvoiceNumber}`,items:replacementItems.map(row=>({productUnitId:row.productUnitId,quantity:row.quantity,unitPrice:row.unitPrice,discountAmount:0,bonusQuantity:0})),payments:context?.partyType==="GUEST"&&difference>0?[{financialAccountId:accountId,paymentAmount:difference,paymentMethod:method,paymentDate:new Date().toISOString()}]:[]}}:{}) } as Parameters<typeof salesApi.createReturn>[1]); if(status === "COMPLETED" && printAfterComplete) await printReceipt(result.data.salesReturnNumber); await onSaved(status === "COMPLETED" ? "Sales Return selesai. Stok, FIFO, piutang, dan kas telah diperbarui." : "Draft Sales Return tersimpan."); }
    catch (caught) { setError(parseApiError(caught)); } finally { setSaving(false); }
  };
  const printReceipt = async (number: string) => {
    if (!context) return;
    const cfg = await systemConfigApi.get();
    const popup = window.open("", "_blank", "width=440,height=760");
    if (!popup) return;
    const escape = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
    const lines = context.details.filter(line => (values[line.salesInvoiceDetailId]?.quantity ?? 0) + (values[line.salesInvoiceDetailId]?.bonusQuantity ?? 0) > 0);
    popup.document.write(`<!doctype html><html><head><title>${escape(number)}</title><style>@page{margin:0}body{font-family:'Courier New',Courier,monospace;font-size:11px;width:58mm;margin:0;padding:6px;color:#000;background:#fff}.c{text-align:center}.r{display:flex;justify-content:space-between}.b{font-weight:700}.line{border-bottom:1px dashed #000;margin:5px 0}.solid{border-bottom:1px solid #000;margin:5px 0}table{width:100%;border-collapse:collapse;font-size:10px}td{padding:2px 0;vertical-align:top}.right{text-align:right}</style></head><body>${cfg.logoBase64?`<div class="c"><img src="${escape(cfg.logoBase64)}" style="max-height:40px;filter:grayscale(100%) contrast(150%)"/></div>`:""}<div class="c b" style="font-size:13px;margin-top:4px">${escape(cfg.companyName)}</div><div class="c">${escape(cfg.address)}</div><div class="c">Telp: ${escape(cfg.phone)}</div>${[cfg.receiptHeader1,cfg.receiptHeader2,cfg.receiptHeader3].filter(Boolean).map(item=>`<div class="c">${escape(item)}</div>`).join("")}<div class="line"></div><div class="c b">SALES RETURN</div><div class="line"></div><div>No. Retur : ${escape(number)}</div><div>Invoice   : ${escape(context.salesInvoiceNumber)}</div><div>Customer  : ${escape(context.customerName)}</div><div class="solid"></div><table>${lines.map(line=>`<tr><td>${escape(line.productName)} (${escape(line.unitName)})</td><td class="right">${values[line.salesInvoiceDetailId]?.quantity||0}x</td></tr><tr><td></td><td class="right">Rp ${((values[line.salesInvoiceDetailId]?.quantity||0)*(line.soldQuantity?line.subtotal/line.soldQuantity:line.unitPrice)).toLocaleString("id-ID")}</td></tr>`).join("")}</table><div class="solid"></div><div class="r b"><span>TOTAL RETUR</span><span>Rp ${total.toLocaleString("id-ID")}</span></div>${note?`<div style="margin-top:4px"><b>Catatan:</b> ${escape(note)}</div>`:""}<div class="line"></div>${[cfg.receiptFooter1,cfg.receiptFooter2,cfg.receiptFooter3].filter(Boolean).map(item=>`<div class="c">${escape(item)}</div>`).join("")}<div class="c" style="font-size:9px;margin-top:6px;color:#555">Dicetak: ${escape(new Date().toLocaleString("id-ID"))}</div></body></html>`);
    popup.document.close(); popup.focus(); popup.print();
  };
  return <Dialog open onOpenChange={(open)=>!open&&onClose()}><DialogOverlay className="fixed inset-0 z-50 bg-black/55"/><DialogContent className="z-[60] flex h-[92dvh] max-h-[92dvh] flex-col overflow-hidden rounded-xl border-slate-200 bg-white p-0 shadow-2xl" style={{width:"1180px",maxWidth:"calc(100vw - 16px)"}}><DialogHeader className="shrink-0 border-b bg-white px-4 py-4 sm:px-6"><DialogTitle className="flex flex-wrap items-center gap-2 text-base font-black uppercase"><span className="flex items-center gap-2"><RotateCcw className="h-5 w-5 text-rose-600"/>Buat Sales Return</span><span className="text-xs font-bold text-slate-500">{context?.salesInvoiceNumber}</span></DialogTitle><p className="text-xs text-slate-500">Pilih barang yang dikembalikan, lalu tentukan pengembalian uang atau barang pengganti.</p></DialogHeader><div className="min-h-0 flex-1 space-y-4 overflow-y-auto overscroll-contain p-4 sm:p-6">
    {error&&<div className="flex gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertTriangle className="h-5 w-5 shrink-0"/>{error}</div>}
    {!context?<div className="flex min-h-72 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-blue-600"/></div>:<><section className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-sm font-black text-slate-900">Riwayat Sales Return</h3><p className="text-[11px] text-slate-500">Retur yang pernah dibuat dari invoice ini.</p></div><Button onClick={()=>setShowForm(value=>!value)} className="text-xs font-bold">{showForm&&context.returns.length?"Lihat Riwayat":"+ Buat Retur Baru"}</Button></div>{!showForm&&<div className="mt-3 grid gap-3 md:grid-cols-2">{context.returns.map(item=><article key={item.salesReturnId} className={`rounded-xl border p-4 ${item.status==="COMPLETED"?"border-emerald-200 bg-emerald-50":item.status==="CANCELLED"?"border-slate-200 bg-slate-100":"border-amber-200 bg-amber-50"}`}><div className="flex items-start justify-between gap-2"><strong>{item.salesReturnNumber}</strong><span className="rounded-full bg-white px-2 py-1 text-[9px] font-black">{item.status}</span></div><p className="mt-2 text-xs font-bold text-slate-600">{item.resolutionType==="REFUND"?"Pengembalian Uang":"Barang Pengganti"}</p><div className="mt-3 flex justify-between text-xs"><span>{new Date(item.returnDate).toLocaleDateString("id-ID")}</span><strong>Rp {item.returnTotal.toLocaleString("id-ID")}</strong></div></article>)}{!context.returns.length&&<div className="py-8 text-center text-xs text-slate-500">Belum ada Sales Return.</div>}</div>}</section><div className={showForm?"space-y-4":"hidden"}><section className="grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 md:grid-cols-3"><label className="text-xs font-black text-slate-700">Jenis Penyelesaian<select className="sales-input mt-1 bg-white" value={resolution} onChange={e=>setResolution(e.target.value as typeof resolution)}><option value="REFUND">Pengembalian Uang</option><option value="REPLACEMENT">Barang Pengganti</option></select></label><label className="text-xs font-black text-slate-700">Akun Kas / Bank<select className="sales-input mt-1 bg-white" value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Pilih akun jika ada selisih uang...</option>{accounts.map(a=><option key={a.financialAccountId} value={a.financialAccountId}>{a.accountName} · Rp {a.currentBalance.toLocaleString("id-ID")}</option>)}</select></label><label className="text-xs font-black text-slate-700">Cara Pengembalian<select className="sales-input mt-1 bg-white" value={method} onChange={e=>setMethod(e.target.value)}><option value="CASH">Tunai</option><option value="TRANSFER">Transfer</option><option value="QRIS">QRIS</option></select></label></section>
    <div className="overflow-x-auto rounded-xl border"><table className="min-w-[760px] w-full text-xs"><thead className="bg-slate-100 text-left text-[10px] uppercase text-slate-500"><tr><th className="p-3">Produk</th><th className="p-3">Dapat Diretur</th><th className="p-3">Qty Normal</th><th className="p-3">Bonus Tersedia</th><th className="p-3">Qty Bonus</th><th className="p-3">Alasan</th></tr></thead><tbody>{context.details.map(line=>{const current=values[line.salesInvoiceDetailId]??{quantity:0,bonusQuantity:0,reason:""};const update=(next:Partial<typeof current>)=>setValues(old=>({...old,[line.salesInvoiceDetailId]:{...current,...next}}));return <tr key={line.salesInvoiceDetailId} className="border-t"><td className="p-3 font-bold">{line.productName}<br/><span className="font-normal text-slate-500">{line.unitName}</span></td><td className="p-3">{line.returnableQuantity}</td><td className="p-3"><input type="number" min={0} max={line.returnableQuantity} className="sales-input w-24" value={current.quantity||""} onChange={e=>update({quantity:Number(e.target.value)})}/></td><td className="p-3">{line.returnableBonusQuantity}</td><td className="p-3"><input type="number" min={0} max={line.returnableBonusQuantity} className="sales-input w-24" value={current.bonusQuantity||""} onChange={e=>update({bonusQuantity:Number(e.target.value)})}/></td><td className="p-3"><input className="sales-input min-w-44" value={current.reason} onChange={e=>update({reason:e.target.value})} placeholder="Contoh: salah barang"/></td></tr>})}</tbody></table></div>
    {resolution==="REPLACEMENT"&&<section className="space-y-3 rounded-xl border border-blue-200 bg-blue-50 p-4"><div><h3 className="text-sm font-black text-blue-900">Sales Invoice Barang Pengganti</h3><p className="text-[11px] text-blue-700">Pilih barang pengganti. Sistem membuat SI baru dan menautkannya ke retur ini.</p></div>{replacementRows.map((row,index)=><div key={index} className="grid gap-2 rounded-lg bg-white p-3 sm:grid-cols-[1fr_110px_160px_auto]"><select className="sales-input" value={row.productUnitId} onChange={e=>{const selected=products.flatMap(p=>p.units.map(u=>({p,u}))).find(x=>x.u.productUnitId===e.target.value);setReplacementRows(old=>old.map((item,i)=>i===index?{...item,productUnitId:e.target.value,unitPrice:selected?.u.suggestedPrice??0}:item))}}><option value="">Pilih produk dan satuan...</option>{products.flatMap(product=>product.units.map(unit=><option key={unit.productUnitId} value={unit.productUnitId}>{product.productName} · {unit.unitName}</option>))}</select><input type="number" min={0.001} className="sales-input" value={row.quantity||""} placeholder="Qty" onChange={e=>setReplacementRows(old=>old.map((item,i)=>i===index?{...item,quantity:Number(e.target.value)}:item))}/><input type="number" min={0} className="sales-input" value={row.unitPrice||""} placeholder="Harga" onChange={e=>setReplacementRows(old=>old.map((item,i)=>i===index?{...item,unitPrice:Number(e.target.value)}:item))}/><Button variant="outline" onClick={()=>setReplacementRows(old=>old.length===1?[{productUnitId:"",quantity:0,unitPrice:0}]:old.filter((_,i)=>i!==index))}>Hapus</Button></div>)}<div className="flex flex-wrap items-end justify-between gap-3"><Button variant="outline" onClick={()=>setReplacementRows(old=>[...old,{productUnitId:"",quantity:0,unitPrice:0}])}>+ Tambah Barang</Button>{context.partyType==="CUSTOMER"&&<label className="text-xs font-bold">Jatuh Tempo Selisih<input type="date" className="sales-input mt-1" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label>}<div className="text-right"><p className="text-[10px] font-black text-blue-600">TOTAL BARANG PENGGANTI</p><p className="font-black">Rp {replacementTotal.toLocaleString("id-ID")}</p></div></div></section>}
    <div className="grid gap-3 sm:grid-cols-[1fr_240px]"><textarea className="sales-input min-h-20" value={note} onChange={e=>setNote(e.target.value)} placeholder="Catatan retur (opsional)..."/><div className="rounded-xl bg-slate-900 p-4 text-white"><p className="text-[10px] font-black uppercase text-slate-400">Nilai Retur Normal</p><p className="mt-1 text-xl font-black">Rp {total.toLocaleString("id-ID")}</p><p className="mt-1 text-[10px] text-slate-300">Barang bonus mengembalikan stok, tanpa nilai uang.</p></div></div></div></>}
  </div><div className="flex shrink-0 flex-wrap items-center justify-end gap-2 border-t bg-white px-4 py-3 sm:px-6">{showForm&&<label className="mr-auto flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" checked={printAfterComplete} onChange={e=>setPrintAfterComplete(e.target.checked)}/>Cetak setelah selesai</label>}<Button variant="outline" onClick={onClose}>Tutup</Button>{showForm&&<><Button variant="outline" disabled={saving||!context} onClick={()=>setPendingStatus("DRAFT")}>Simpan Draft</Button><Button disabled={saving||!context} className="bg-emerald-600 hover:bg-emerald-700" onClick={()=>setPendingStatus("COMPLETED")}>{saving?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:null}Selesaikan Retur</Button></>}</div></DialogContent><AlertDialog open={pendingStatus!==null} onOpenChange={open=>!open&&!saving&&setPendingStatus(null)}><AlertDialogContent className="bg-white"><AlertDialogHeader><AlertDialogTitle>{pendingStatus==="COMPLETED"?"Selesaikan Sales Return?":"Simpan sebagai Draft?"}</AlertDialogTitle><AlertDialogDescription>{pendingStatus==="COMPLETED"?"Stok, FIFO, piutang, dan Kas/Bank akan diproses. Sales Return yang selesai tidak dapat diedit kembali.":"Data retur akan disimpan sebagai Draft dan belum memengaruhi stok, FIFO, maupun keuangan."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={saving}>Kembali</AlertDialogCancel><AlertDialogAction disabled={saving} className={pendingStatus==="COMPLETED"?"bg-emerald-600 text-white":"bg-blue-600 text-white"} onClick={event=>{event.preventDefault();const status=pendingStatus;if(!status)return;void submit(status).then(()=>setPendingStatus(null))}}>Ya, {pendingStatus==="COMPLETED"?"Selesaikan":"Simpan Draft"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></Dialog>;
}
