/**
 * Canonical business-document origins for every inventory and FIFO record.
 * `originId` must always reference the document header represented here.
 */
export const INVENTORY_ORIGIN_TYPES = {
  PURCHASE_INVOICE: 'PURCHASE_INVOICE',
  PURCHASE_RETURN: 'PURCHASE_RETURN',
  SALES_INVOICE: 'SALES_INVOICE',
  SALES_RETURN: 'SALES_RETURN',
  INVENTORY_ADJUSTMENT: 'INVENTORY_ADJUSTMENT',
  INVENTORY_TRANSFORMATION: 'INVENTORY_TRANSFORMATION',
  INVENTORY_LOAN: 'INVENTORY_LOAN',
  INVENTORY_LOAN_RETURN: 'INVENTORY_LOAN_RETURN',
  OPENING_BALANCE: 'OPENING_BALANCE',
} as const;

export type InventoryOriginType =
  (typeof INVENTORY_ORIGIN_TYPES)[keyof typeof INVENTORY_ORIGIN_TYPES];

/** Describes the stock event; it is deliberately separate from document origin. */
export const INVENTORY_MOVEMENT_TYPES = {
  PURCHASE_RECEIPT: 'PURCHASE_RECEIPT',
  PURCHASE_RETURN_OUT: 'PURCHASE_RETURN_OUT',
  PURCHASE_REPLACEMENT_IN: 'PURCHASE_REPLACEMENT_IN',
  PURCHASE_RETURN_CANCEL_IN: 'PURCHASE_RETURN_CANCEL_IN',
  SALES_ISSUE: 'SALES_ISSUE',
  SALES_RETURN_IN: 'SALES_RETURN_IN',
  ADJUSTMENT_IN: 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT: 'ADJUSTMENT_OUT',
  TRANSFORMATION_SOURCE_OUT: 'TRANSFORMATION_SOURCE_OUT',
  TRANSFORMATION_RESULT_IN: 'TRANSFORMATION_RESULT_IN',
  INVENTORY_LOAN_OUT: 'INVENTORY_LOAN_OUT',
  INVENTORY_LOAN_RETURN_IN: 'INVENTORY_LOAN_RETURN_IN',
  OPENING_BALANCE_IN: 'OPENING_BALANCE_IN',
} as const;

export type InventoryMovementType =
  (typeof INVENTORY_MOVEMENT_TYPES)[keyof typeof INVENTORY_MOVEMENT_TYPES];
